import { format } from "prettier";
import {
  campaignCollection,
  campaignSchemaVersion,
} from "../../apps/campaign-site/src/campaign-schema.mjs";

function fieldType(field) {
  switch (field.type) {
    case "string":
    case "text":
    case "url":
      return "string";
    case "portableText":
      return "PortableTextBlock[]";
    case "select": {
      const options = field.validation?.options ?? field.options;
      if (
        !Array.isArray(options) ||
        !options.length ||
        options.some((option) => typeof option !== "string")
      ) {
        throw new Error("campaign_typegen_invalid_select");
      }
      return options.map((option) => JSON.stringify(option)).join(" | ");
    }
    case "repeater": {
      const fields = field.validation?.subFields;
      if (!Array.isArray(fields) || !fields.length) {
        throw new Error("campaign_typegen_invalid_repeater");
      }
      // EmDash's native repeater includes a stable editor row key.
      return `{ _key?: string; ${fields.map(property).join("\n")} }[]`;
    }
    default:
      throw new Error("campaign_typegen_unsupported_field");
  }
}

function property(field) {
  if (typeof field.slug !== "string" || !/^[a-z][a-z0-9_]*$/.test(field.slug)) {
    throw new Error("campaign_typegen_invalid_field");
  }
  return `${JSON.stringify(field.slug)}${field.required ? "" : "?"}: ${fieldType(field)}${field.required ? "" : " | null"};`;
}

// Build/operator tooling only. Types describe CMS field values, not validated
// public content or authority to read it. The runtime validator remains required.
export async function generateCampaignTypes(collection = campaignCollection) {
  if (collection.slug !== "campaign_pages") {
    throw new Error("campaign_typegen_wrong_collection");
  }
  const fields = [...collection.fields].sort((a, b) =>
    a.slug < b.slug ? -1 : a.slug > b.slug ? 1 : 0,
  );
  if (new Set(fields.map((field) => field.slug)).size !== fields.length) {
    throw new Error("campaign_typegen_duplicate_field");
  }
  return format(
    `// Generated by ./leonaid export-campaign-types; do not edit manually.
// Field shapes only: authorization and campaignEditorial validation are required.
import type { PortableTextBlock } from "emdash";

export type CampaignSchemaVersion = ${campaignSchemaVersion};

export interface CampaignPageFields {
${fields.map(property).join("\n")}
}
`,
    { parser: "typescript" },
  );
}
