"""Pre-migration receipts with hashes generated by the pre-delivery application."""

import json
from pathlib import Path
from uuid import UUID

import httpx

from leonaid.adapters.postgres.commitments import AsyncpgCommitmentRepository
from leonaid.adapters.postgres.legal_configuration import (
    AsyncpgLegalConfigurationRepository,
)
from leonaid.adapters.postgres.public_orders import AsyncpgPublicOrderRepository
from leonaid.application.commitments import CommitmentService
from leonaid.application.public_orders import PublicOrderService, PublicOrderTokenCodec
from leonaid.domain.commitments import CommitmentSource, CommitmentStatus
from leonaid.domain.identity import (
    AccountStatus,
    GlobalRole,
    IdentityPrincipal,
    UserAccount,
)
from leonaid.entrypoints.fastapi.routes import commitment_draft, public_order_draft
from leonaid.entrypoints.fastapi.schemas import (
    CreateCommitmentRequest,
    CreatePublicOrderRequest,
)
from tools.delivery.http_configuration import http_app


def fixture():
    return json.loads(Path("tools/delivery/legacy-replay.json").read_text())


def seed_receipts(db):
    data = fixture()
    old = data["internal"]
    public = data["public"]
    public_key = f"public.order:{data['actionId']}:{public['body']['commandId']}"
    db.execute(
        """INSERT INTO commitment(id,action_id,twenty_company_id,source,status,
          customer_snapshot,invoice_recipient_snapshot,delivery_recipient_snapshot,
          currency,total_minor,idempotency_key,public_reference)
        SELECT %s,action_id,twenty_company_id,'public_form','review_ready',
          customer_snapshot,invoice_recipient_snapshot,invoice_recipient_snapshot - 'email',
          currency,total_minor,%s,'LA-80000000000040008000000000000099'
        FROM commitment WHERE id=%s""",
        (public["commitmentId"], public_key, old["commitmentId"]),
    )
    db.execute(
        """INSERT INTO commitment_line(id,commitment_id,offering_id,description_snapshot,
          quantity,unit_snapshot,pieces_per_unit_snapshot,unit_price_minor,line_total_minor)
        SELECT '81000000-0000-4000-8000-000000000099',%s,offering_id,description_snapshot,
          quantity,unit_snapshot,pieces_per_unit_snapshot,unit_price_minor,line_total_minor
        FROM commitment_line WHERE commitment_id=%s""",
        (public["commitmentId"], old["commitmentId"]),
    )
    for key, command_type, request_hash, result in (
        (
            old["idempotencyKey"],
            "create_commitment_v1",
            old["requestHash"],
            {"commitmentId": old["commitmentId"]},
        ),
        (
            public_key,
            "create_public_order_v1",
            public["requestHash"],
            {
                "commitmentId": public["commitmentId"],
                "contactTwentyId": None,
                "crmOutcome": "reused",
                "activityRecipientIds": [],
            },
        ),
    ):
        db.execute(
            "INSERT INTO command_receipt(idempotency_key,command_type,request_hash,result,completed_at) VALUES (%s,%s,%s,%s::jsonb,CURRENT_TIMESTAMP)",
            (key, command_type, request_hash, json.dumps(result)),
        )


class NoCrm:
    def __getattr__(self, name):
        raise AssertionError(f"Legacy replay accessed CRM: {name}")


async def prove_legacy_replay(pool, admin_id):
    data = fixture()
    action_id = UUID(data["actionId"])
    old = data["internal"]
    public = data["public"]
    actor = IdentityPrincipal(
        UserAccount(admin_id, "admin@example.invalid", "Test", AccountStatus.ACTIVE),
        frozenset({GlobalRole.SYSTEM_ADMIN}),
        (),
    )
    app, identity = http_app(actor)
    app.state.commitment_service = CommitmentService(AsyncpgCommitmentRepository(pool))
    secret = "synthetic-delivery-legacy-replay-secret"
    service = PublicOrderService(
        AsyncpgPublicOrderRepository(pool),
        NoCrm(),
        PublicOrderTokenCodec(secret),
        AsyncpgLegalConfigurationRepository(pool),
    )
    app.state.public_order_service = service
    app.state.public_order_fingerprint_secret = secret
    public_body = {
        **public["body"],
        "accessToken": service.issue_access_token(action_id, public["publicAlias"]),
    }
    assert (
        commitment_draft(
            CreateCommitmentRequest.model_validate(old["body"])
        ).fingerprint(
            action_id=action_id,
            source=CommitmentSource.ADMIN,
            status=CommitmentStatus.REVIEW_READY,
        )
        == old["requestHash"]
    )
    assert (
        public_order_draft(
            CreatePublicOrderRequest.model_validate(public_body)
        ).request_hash(action_id=action_id, public_alias=public["publicAlias"])
        == public["requestHash"]
    )
    count = await pool.fetchval("SELECT count(*) FROM commitment")
    async with httpx.AsyncClient(
        transport=httpx.ASGITransport(app=app), base_url="http://test"
    ) as client:
        internal_path = f"/api/v1/actions/{action_id}/commitments"
        response = await client.post(
            internal_path,
            json=old["body"],
            headers={"Idempotency-Key": old["idempotencyKey"]},
        )
        assert response.status_code == 201, response.text
        assert (
            response.json()["id"] == old["commitmentId"] and response.json()["replayed"]
        )
        assert response.json()["deliveryWindowId"] is None
        identity.current = None
        public_path = f"/api/v1/public/actions/{public['publicAlias']}/orders"
        response = await client.post(public_path, json=public_body)
        assert response.status_code == 200, response.text
        assert (
            response.json()["commitmentId"] == public["commitmentId"]
            and response.json()["replayed"]
        )
        changed = await client.post(
            public_path, json={**public_body, "deliveryContact": {"name": "Changed"}}
        )
        assert changed.status_code == 409
    assert await pool.fetchval("SELECT count(*) FROM commitment") == count
    print(
        "KLF-030 legacy replay PASS: persisted pre-migration internal/public receipts, pre-delivery f12a035 hashes, absent new fields, actual HTTP replay without CRM or duplicate orders, changed request conflict"
    )
