FROM docker.io/library/node:22.23.0-alpine3.23@sha256:35e2f96595091599e7c1fb0b61049e17d8478997b2aa13db51ad7995299fe55a

WORKDIR /app
RUN rm -rf /opt/yarn-v1.22.22 /usr/local/lib/node_modules/corepack /usr/local/lib/node_modules/npm
COPY infra/compose/static-server.mjs ./static-server.mjs
USER node
EXPOSE 3000
CMD ["node", "static-server.mjs"]
