FROM docker.io/library/node:22.17.1-alpine3.22@sha256:5539840ce9d013fa13e3b9814c9353024be7ac75aca5db6d039504a56c04ea59

WORKDIR /app
COPY infra/compose/static-server.mjs ./static-server.mjs
USER node
EXPOSE 3000
CMD ["node", "static-server.mjs"]
