// Generated by ./leonaid export-campaign-types; do not edit manually.
// Field shapes only: authorization and campaignEditorial validation are required.
import type { PortableTextBlock } from "emdash";

export type CampaignSchemaVersion = 1;

export interface CampaignPageFields {
  action_id: string;
  body?: PortableTextBlock[] | null;
  faq?: { _key?: string; question: string; answer: string }[] | null;
  hero_summary?: string | null;
  hero_title?: string | null;
  partners?:
    | {
        _key?: string;
        name: string;
        description?: string | null;
        website?: string | null;
      }[]
    | null;
  seo_description?: string | null;
  theme?: "leonaid" | "krapfentaxi" | null;
  title?: string | null;
}
