// Generated by ./leonaid export-campaign-types; do not edit manually.
// Field shapes only: authorization and campaignEditorial validation are required.
import type { PortableTextBlock } from "emdash";

export type CampaignSchemaVersion = 3;

export interface CampaignImageReference {
  id: string;
  provider?: "local";
  alt?: string;
  width?: number;
  height?: number;
  filename?: string;
  mimeType?: "image/png" | "image/jpeg" | "image/webp";
  meta?: {
    storageKey: string;
    caption?: string | null;
    blurhash?: string | null;
    dominantColor?: string | null;
  };
}

export interface CampaignPageFields {
  action_id: string;
  body?: PortableTextBlock[] | null;
  brand_logo?: CampaignImageReference | null;
  faq?: { _key?: string; question: string; answer: string }[] | null;
  hero_image?: CampaignImageReference | null;
  hero_summary?: string | null;
  hero_title?: string | null;
  partners?:
    | {
        _key?: string;
        name: string;
        description?: string | null;
        website?: string | null;
        logo?: CampaignImageReference | null;
        eyebrow?: string | null;
        link_label?: string | null;
      }[]
    | null;
  seo_description?: string | null;
  social_image?: CampaignImageReference | null;
  story_eyebrow?: string | null;
  story_title?: string | null;
  theme?: "leonaid" | "krapfentaxi" | null;
  title?: string | null;
}
