/* eslint-disable */
// Generated by tools/openapi/generate.py. Do not edit.

export type AcceptInvitationRequest = { readonly code?: string | null; readonly email?: string | null; readonly magicToken?: string | null; };
export type ApiErrorDetail = { readonly code: string; readonly message: string; readonly requestId: string; };
export type ApiErrorResponse = { readonly error: ApiErrorDetail; };
export type CreateInvitationRequest = { readonly actionId: string; readonly displayName: string; readonly email: string; readonly role: "charity_admin" | "acquirer" | "finance_reader" | "driver"; };
export type CurrentIdentityResponse = { readonly actionMemberships: Array<IdentityMembershipResponse>; readonly displayName: string; readonly globalRoles: Array<"system_admin" | "finance_reader" | "finance_manager">; readonly navigation: Array<NavigationItemResponse>; readonly roleLabels: Array<string>; readonly userId: string; };
export type DependencyStatusResponse = { readonly details: Record<string, string | number | boolean>; readonly status: "ready" | "not-ready"; };
export type IdentityMembershipResponse = { readonly actionId: string; readonly actionName: string; readonly role: "charity_admin" | "acquirer" | "finance_reader" | "driver"; readonly roleLabel: string; };
export type InvitationAcceptanceResponse = { readonly actionId: string; readonly actionName: string; readonly role: "charity_admin" | "acquirer" | "finance_reader" | "driver"; readonly status: "accepted"; };
export type InvitationDispatchResponse = { readonly invitationId: string; readonly status: "queued"; };
export type InvitationOptionsResponse = { readonly actions: Array<InviteableActionResponse>; readonly roles: Array<InvitationRoleOptionResponse>; };
export type InvitationRevocationResponse = { readonly status: "revoked"; };
export type InvitationRoleOptionResponse = { readonly label: string; readonly value: "charity_admin" | "acquirer" | "finance_reader" | "driver"; };
export type InviteableActionResponse = { readonly id: string; readonly name: string; readonly status: "draft" | "scheduled" | "active"; };
export type NavigationItemResponse = { readonly href: string; readonly key: string; readonly label: string; readonly surface: "web" | "pwa"; };
export type PlatformInformationResponse = { readonly apiVersion: string; readonly release: string; readonly service: string; };
export type PlatformStatusResponse = { readonly service: string; readonly status: "live"; };
export type ReadinessResponse = { readonly checks: Record<string, DependencyStatusResponse>; readonly service: string; readonly status: "ready" | "not-ready"; };

export type FetchLike = (
  input: RequestInfo | URL,
  init?: RequestInit,
) => Promise<Response>;

export interface RequestOptions {
  readonly signal?: AbortSignal;
  readonly headers?: Readonly<Record<string, string>>;
}

export class ApiError extends Error {
  readonly status: number;
  readonly detail: ApiErrorDetail;

  constructor(status: number, detail: ApiErrorDetail) {
    super(detail.message);
    this.name = "ApiError";
    this.status = status;
    this.detail = detail;
  }
}

export class LeonAidApiClient {
  readonly #baseUrl: string;
  readonly #fetch: FetchLike;

  constructor(baseUrl: string, fetcher: FetchLike = globalThis.fetch) {
    this.#baseUrl = baseUrl.replace(/\/$/, "");
    this.#fetch = fetcher;
  }

  async request<T>(
    path: string,
    init: RequestInit,
    options: RequestOptions = {},
  ): Promise<T> {
    const response = await this.#fetch(`${this.#baseUrl}${path}`, {
      ...init,
      headers: {
        Accept: "application/json",
        ...(init.headers as Readonly<Record<string, string>> | undefined),
        ...options.headers,
      },
      signal: options.signal,
    });
    const body = await response.json() as unknown;
    if (!response.ok) {
      if (isApiErrorResponse(body)) {
        throw new ApiError(response.status, body.error);
      }
      throw new Error(`LeonAid API returned HTTP ${response.status}`);
    }
    return body as T;
  }

  async getCurrentIdentity(
    options: RequestOptions = {},
  ): Promise<CurrentIdentityResponse> {
    return this.request<CurrentIdentityResponse>(
      "/api/v1/identity/me",
      { method: "GET" },
      options,
    );
  }

  async createInvitation(
    body: CreateInvitationRequest,
    options: RequestOptions = {},
  ): Promise<InvitationDispatchResponse> {
    return this.request<InvitationDispatchResponse>(
      "/api/v1/invitations",
      {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
      },
      options,
    );
  }

  async acceptInvitation(
    body: AcceptInvitationRequest,
    options: RequestOptions = {},
  ): Promise<InvitationAcceptanceResponse> {
    return this.request<InvitationAcceptanceResponse>(
      "/api/v1/invitations/accept",
      {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
      },
      options,
    );
  }

  async getInvitationOptions(
    options: RequestOptions = {},
  ): Promise<InvitationOptionsResponse> {
    return this.request<InvitationOptionsResponse>(
      "/api/v1/invitations/options",
      { method: "GET" },
      options,
    );
  }

  async revokeInvitation(
    invitationId: string,
    options: RequestOptions = {},
  ): Promise<InvitationRevocationResponse> {
    return this.request<InvitationRevocationResponse>(
      `/api/v1/invitations/${encodeURIComponent(String(invitationId))}`,
      { method: "DELETE" },
      options,
    );
  }

  async getPlatformInformation(
    options: RequestOptions = {},
  ): Promise<PlatformInformationResponse> {
    return this.request<PlatformInformationResponse>(
      "/api/v1/platform",
      { method: "GET" },
      options,
    );
  }

  async getHealthLive(
    options: RequestOptions = {},
  ): Promise<PlatformStatusResponse> {
    return this.request<PlatformStatusResponse>(
      "/health/live",
      { method: "GET" },
      options,
    );
  }

  async getHealthReady(
    options: RequestOptions = {},
  ): Promise<ReadinessResponse> {
    return this.request<ReadinessResponse>(
      "/health/ready",
      { method: "GET" },
      options,
    );
  }
}

function isApiErrorResponse(value: unknown): value is ApiErrorResponse {
  if (typeof value !== "object" || value === null || !("error" in value)) {
    return false;
  }
  const error = value.error;
  return typeof error === "object" && error !== null
    && "code" in error && typeof error.code === "string"
    && "message" in error && typeof error.message === "string"
    && "requestId" in error && typeof error.requestId === "string";
}
