/* eslint-disable */
// Generated by tools/openapi/generate.py. Do not edit.

export type AcceptInvitationRequest = { readonly code?: string | null; readonly email?: string | null; readonly magicToken?: string | null; };
export type AcquirerDashboardResponse = { readonly activityCount: number; readonly pipeline: DashboardPipelineResponse; readonly reminders: DashboardReminderResponse; };
export type AcquisitionActivityBoardResponse = { readonly actionId: string; readonly activities: Array<RecordedAcquisitionActivityResponse>; readonly generatedAt: string; readonly workItems: Array<AcquisitionActivityWorkItemResponse>; };
export type AcquisitionActivityListResponse = { readonly items: Array<AcquisitionActivityResponse>; readonly limit: number; readonly offset: number; readonly total: number; };
export type AcquisitionActivityResponse = { readonly actionId: string; readonly actorUserId: string | null; readonly channel: string; readonly id: string; readonly note: string | null; readonly occurredAt: string; readonly outcome: string; readonly partyId: string; readonly partyKind: "company" | "person"; };
export type AcquisitionActivityWorkItemResponse = { readonly assignedAcquirers: Array<AssignedAcquirerResponse>; readonly assignmentId: string; readonly city: string | null; readonly contactName: string | null; readonly dueAt: string | null; readonly email: string | null; readonly nextAction: string | null; readonly partyDisplayName: string; readonly partyId: string; readonly partyKind: "company" | "person"; readonly phone: string | null; readonly postalCode: string | null; readonly priority: number; readonly revision: number; readonly status: "open" | "contacted" | "committed" | "declined" | "handed_over"; readonly suppressedChannels: Array<"email" | "phone" | "postal">; readonly urgency: "overdue" | "today" | "upcoming" | "none"; };
export type AcquisitionAssignmentDetailsResponse = { readonly assignment: AcquisitionAssignmentResponse; readonly history: Array<AcquisitionAssignmentHistoryResponse>; };
export type AcquisitionAssignmentHandoverResponse = { readonly source: AcquisitionAssignmentResponse; readonly target: AcquisitionAssignmentResponse; readonly targetCreated: boolean; };
export type AcquisitionAssignmentHistoryResponse = { readonly assignmentId: string; readonly changedAt: string; readonly changedByDisplayName: string; readonly changedByUserId: string; readonly id: string; readonly newState: Record<string, unknown>; readonly previousState: Record<string, unknown>; };
export type AcquisitionAssignmentMutationResponse = { readonly assignment: AcquisitionAssignmentResponse; readonly created: boolean; };
export type AcquisitionAssignmentResponse = { readonly acquirerDisplayName: string; readonly acquirerUserId: string; readonly actionId: string; readonly createdAt: string; readonly dueAt: string | null; readonly id: string; readonly nextAction: string | null; readonly partyId: string; readonly partyKind: "company" | "person"; readonly priority: number; readonly revision: number; readonly status: "open" | "contacted" | "committed" | "declined" | "handed_over"; readonly updatedAt: string; };
export type AcquisitionDocumentResponse = { readonly actionId: string; readonly createdAt: string; readonly documentType: string; readonly id: string; readonly mediaType: string; readonly partyId: string; readonly partyKind: "company" | "person"; readonly sha256: string; readonly version: number; };
export type AcquisitionPartyCountResponse = { readonly total: number; };
export type AcquisitionPartyExportResponse = { readonly actionId: string; readonly items: Array<AcquisitionPartyResponse>; };
export type AcquisitionPartyListResponse = { readonly items: Array<AcquisitionPartyResponse>; readonly limit: number; readonly offset: number; readonly total: number; };
export type AcquisitionPartyResponse = { readonly assignedAcquirerIds: Array<string>; readonly city: string | null; readonly displayName: string; readonly email: string | null; readonly partyKind: "company" | "person"; readonly postalCode: string | null; readonly twentyId: string; };
export type ActionGoalRequest = { readonly actualValue?: string; readonly currency?: string | null; readonly goalValue?: string | null; readonly unit?: string | null; };
export type ActionGoalResponse = { readonly actualValue: string; readonly currency: string | null; readonly goalValue: string | null; readonly unit: string | null; };
export type ActionManagementResponse = { readonly action: CharityActionResponse; readonly administratorOptions: Array<AdministratorOptionResponse>; readonly allowedTransitions: Array<"draft" | "scheduled" | "active" | "completed" | "archived">; readonly publicAlias: string | null; };
export type ActionTemplateListResponse = { readonly items: Array<ActionTemplateSummaryResponse>; };
export type ActionTemplateSnapshotResponse = { readonly copiedFromActionId: string | null; readonly displayName: string; readonly key: "blank" | "krapfentaxi"; readonly version: number; };
export type ActionTemplateSummaryResponse = { readonly capabilities: Array<"acquisition" | "offerings" | "ordering" | "invoicing">; readonly description: string; readonly displayName: string; readonly hasOrderForm: boolean; readonly key: "blank" | "krapfentaxi"; readonly offeringCount: number; readonly version: number; };
export type ActivityFeedItemResponse = { readonly actionId: string; readonly actionName: string; readonly commitmentId: string; readonly currency: string; readonly eventType: "public_order_received"; readonly id: string; readonly isRead: boolean; readonly nextActionHref: string; readonly nextActionLabel: string; readonly occurredAt: string; readonly partyDisplayName: string; readonly partyId: string; readonly partyKind: "company" | "person"; readonly publicReference: string; readonly readAt: string | null; readonly totalBoxes: number; readonly totalMinor: number; readonly totalPieces: number; };
export type ActivityFeedResponse = { readonly items: Array<ActivityFeedItemResponse>; readonly limit: number; readonly offset: number; readonly total: number; readonly unreadCount: number; };
export type AdministratorOptionResponse = { readonly displayName: string; readonly email: string; readonly isAvailable: boolean; readonly isResponsible: boolean; readonly userId: string; };
export type ApiErrorDetail = { readonly code: string; readonly message: string; readonly requestId: string; };
export type ApiErrorResponse = { readonly error: ApiErrorDetail; };
export type AssignedAcquirerResponse = { readonly displayName: string; readonly userId: string; };
export type BeneficiaryDraftRequest = { readonly organizationName: string; readonly publicDescription: string; };
export type BeneficiaryResponse = { readonly id: string; readonly organizationName: string; readonly publicDescription: string; readonly sortOrder: number; };
export type CancelInvoiceRequest = { readonly reason: string; };
export type CharityActionConfigurationResponse = { readonly action: CharityActionResponse; readonly offerings: Array<ConfiguredOfferingResponse>; readonly orderForm: OrderFormConfigurationResponse | null; readonly template: ActionTemplateSnapshotResponse; };
export type CharityActionResponse = { readonly archiveSlug: string; readonly beneficiaries: Array<BeneficiaryResponse>; readonly capabilities: Array<"acquisition" | "offerings" | "ordering" | "invoicing">; readonly carrierName: string; readonly endsOn: string; readonly goal: ActionGoalResponse; readonly id: string; readonly name: string; readonly publicationEndsAt: string | null; readonly publicationStartsAt: string | null; readonly purpose: string; readonly revision: number; readonly startsOn: string; readonly status: "draft" | "scheduled" | "active" | "completed" | "archived"; };
export type CharityAdminDashboardResponse = { readonly commitments: DashboardCommitmentResponse; readonly invoices: DashboardInvoiceResponse; readonly pipeline: DashboardPipelineResponse; };
export type CommitmentBuyerRequest = { readonly displayName: string; readonly email?: string | null; readonly partyKind: "company" | "person"; readonly twentyId: string; };
export type CommitmentBuyerResponse = { readonly displayName: string; readonly email: string | null; readonly partyKind: "company" | "person"; readonly twentyId: string; };
export type CommitmentCaptureContextResponse = { readonly actionId: string; readonly actionName: string; readonly offerings: Array<ConfiguredOfferingResponse>; };
export type CommitmentCurrencyTotalResponse = { readonly currency: string; readonly totalMinor: number; };
export type CommitmentInvoiceRecipientRequest = { readonly city: string; readonly countryCode?: string; readonly email?: string | null; readonly postalCode: string; readonly recipientName: string; readonly streetLine1: string; };
export type CommitmentInvoiceRecipientResponse = { readonly city: string; readonly countryCode: string; readonly email: string | null; readonly postalCode: string; readonly recipientName: string; readonly streetLine1: string; };
export type CommitmentLineRequest = { readonly offeringId: string; readonly quantity: number; readonly quotedUnitPriceMinor?: number | null; readonly unit: "box" | "piece" | "package" | "sponsoring"; };
export type CommitmentLineResponse = { readonly boxCount: number; readonly currency: string; readonly description: string; readonly id: string; readonly lineTotalMinor: number; readonly offeringId: string; readonly pieceCount: number; readonly piecesPerUnit: number | null; readonly quantity: number; readonly unit: "box" | "piece" | "package" | "sponsoring"; readonly unitPriceMinor: number; };
export type CommitmentListResponse = { readonly actionId: string; readonly currencyTotals: Array<CommitmentCurrencyTotalResponse>; readonly items: Array<CommitmentRecordResponse>; readonly totalBoxes: number; readonly totalPieces: number; };
export type CommitmentRecordResponse = { readonly capturedByDisplayName: string | null; readonly commitment: CommitmentResponse; readonly createdAt: string; };
export type CommitmentResponse = { readonly actionId: string; readonly buyer: CommitmentBuyerResponse; readonly currency: string; readonly id: string; readonly invoiceRecipient: CommitmentInvoiceRecipientResponse | null; readonly lines: Array<CommitmentLineResponse>; readonly replayed: boolean; readonly source: "acquisition" | "public_form" | "admin"; readonly status: "draft" | "review_ready" | "confirmed" | "invoiced" | "cancelled"; readonly totalBoxes: number; readonly totalMinor: number; readonly totalPieces: number; };
export type CompleteFreshLoginRequest = { readonly code?: string | null; readonly magicToken?: string | null; };
export type CompleteLoginRequest = { readonly code?: string | null; readonly email?: string | null; readonly magicToken?: string | null; };
export type ConfiguredOfferingResponse = { readonly allowedQuantityUnits: Array<"box" | "piece" | "package" | "sponsoring">; readonly availableFrom: string | null; readonly availableUntil: string | null; readonly code: string; readonly currency: string; readonly id: string; readonly name: string; readonly piecesPerUnit: number | null; readonly status: "draft" | "active" | "inactive"; readonly unit: "box" | "piece" | "package" | "sponsoring"; readonly unitPriceMinor: number; };
export type CopyCharityActionRequest = { readonly archiveSlug: string; readonly endsOn: string; readonly name: string; readonly startsOn: string; };
export type CreateAcquisitionAssignmentRequest = { readonly acquirerUserId: string; readonly partyId: string; readonly partyKind: "company" | "person"; };
export type CreateActionFromTemplateRequest = { readonly archiveSlug: string; readonly beneficiaries: Array<BeneficiaryDraftRequest>; readonly carrierName: string; readonly endsOn: string; readonly goal: ActionGoalRequest; readonly name: string; readonly purpose: string; readonly startsOn: string; readonly templateKey: "blank" | "krapfentaxi"; readonly templateVersion?: number | null; };
export type CreateCharityActionRequest = { readonly archiveSlug: string; readonly beneficiaries: Array<BeneficiaryDraftRequest>; readonly capabilities: Array<"acquisition" | "offerings" | "ordering" | "invoicing">; readonly carrierName: string; readonly endsOn: string; readonly goal: ActionGoalRequest; readonly name: string; readonly purpose: string; readonly startsOn: string; };
export type CreateCommitmentRequest = { readonly buyer: CommitmentBuyerRequest; readonly invoiceRecipient?: CommitmentInvoiceRecipientRequest | null; readonly lines: Array<CommitmentLineRequest>; readonly readyForReview?: boolean; readonly source: "acquisition" | "admin"; };
export type CreateInvitationRequest = { readonly actionId: string; readonly displayName: string; readonly email: string; readonly role: "charity_admin" | "acquirer" | "finance_reader" | "driver"; };
export type CreatePublicOrderRequest = { readonly accessToken: string; readonly bindingOrderConfirmed: boolean; readonly commandId: string; readonly deliveryRecipient: PublicOrderDeliveryRecipientRequest; readonly invoiceRecipient: PublicOrderInvoiceRecipientRequest; readonly lines: Array<PublicOrderLineRequest>; readonly message?: string | null; readonly party: PublicOrderPartyRequest; readonly privacyAcknowledged: boolean; readonly privacyNoticeVersion: "public-order-poc-2026-07"; readonly website?: string | null; };
export type CrmPartyKind = "company" | "person";
export type CurrentIdentityResponse = { readonly actionMemberships: Array<IdentityMembershipResponse>; readonly displayName: string; readonly freshLoginAt: string; readonly freshUntil: string; readonly globalRoles: Array<"system_admin" | "finance_reader" | "finance_manager">; readonly navigation: Array<NavigationItemResponse>; readonly roleLabels: Array<string>; readonly sessionExpiresAt: string; readonly sessionLastSeenAt: string; readonly userId: string; };
export type DashboardCommitmentResponse = { readonly activeTotal: number; readonly activeTotalMinor: number; readonly cancelled: number; readonly confirmed: number; readonly currency: string; readonly draft: number; readonly invoiced: number; readonly reviewReady: number; readonly total: number; readonly totalBoxes: number; readonly totalPieces: number; };
export type DashboardGoalResponse = { readonly actualValue: string; readonly configured: boolean; readonly currency: string; readonly progressBasisPoints?: number | null; readonly targetValue: string | null; readonly unit: string | null; };
export type DashboardInvoiceResponse = { readonly cancelled: number; readonly currency: string; readonly invoicedAmountMinor: number; readonly issued: number; readonly open: number; readonly openAmountMinor: number; readonly paid: number; readonly sent: number; readonly total: number; };
export type DashboardMetricDefinitionResponse = { readonly description: string; readonly href: string; readonly key: string; readonly label: string; };
export type DashboardPipelineResponse = { readonly committed: number; readonly contacted: number; readonly declined: number; readonly handedOver: number; readonly open: number; readonly total: number; };
export type DashboardReminderResponse = { readonly overdue: number; readonly today: number; readonly total: number; readonly unscheduled: number; readonly upcoming: number; };
export type DashboardResponse = { readonly acquirer: AcquirerDashboardResponse | null; readonly actionId: string; readonly actionName: string; readonly charityAdmin: CharityAdminDashboardResponse | null; readonly generatedAt: string; readonly goal: DashboardGoalResponse; readonly metricDefinitions: Array<DashboardMetricDefinitionResponse>; };
export type DependencyStatusResponse = { readonly details: Record<string, string | number | boolean>; readonly status: "ready" | "not-ready"; };
export type FeatureFlagAdminListResponse = { readonly flags: Array<FeatureFlagAdminResponse>; };
export type FeatureFlagAdminResponse = { readonly clientSafe: boolean; readonly defaultEnabled: boolean; readonly description: string; readonly effect: string; readonly enabled: boolean; readonly key: "admin.system_status_panel" | "admin.preview_notice"; readonly revision: number; readonly title: string; readonly updatedAt: string; readonly updatedByUserId: string | null; };
export type FeatureFlagEvaluationListResponse = { readonly flags: Array<FeatureFlagEvaluationResponse>; readonly surface: "web" | "pwa"; };
export type FeatureFlagEvaluationResponse = { readonly enabled: boolean; readonly key: "admin.system_status_panel" | "admin.preview_notice"; readonly provider: string; readonly reason: string; readonly variant: string; };
export type FeatureFlagSystemStatusResponse = { readonly checkedAt: string; readonly evaluatedBy: "openfeature"; readonly provider: string; readonly status: "operational"; };
export type FreshLoginStatusResponse = { readonly freshUntil: string; readonly status: "fresh"; };
export type GeneratedDocumentListResponse = { readonly actionId: string; readonly items: Array<GeneratedDocumentRecordResponse>; readonly reference: GeneratedDocumentReferenceResponse; };
export type GeneratedDocumentRecordResponse = { readonly buyerDisplayName: string; readonly document: GeneratedDocumentResponse; readonly invoiceNumber: string | null; };
export type GeneratedDocumentReferenceResponse = { readonly id: string; readonly kind: "action" | "commitment" | "invoice" | "twenty_company" | "twenty_person"; };
export type GeneratedDocumentResponse = { readonly actionId: string; readonly availableAt: string | null; readonly commitmentId: string | null; readonly createdAt: string; readonly documentType: "invoice_pdf"; readonly filename: string | null; readonly id: string; readonly invoiceId: string | null; readonly mediaType: string; readonly renderVersion: string | null; readonly sentAt: string | null; readonly sizeBytes: number | null; readonly status: "pending" | "available" | "deleted"; readonly twentyCompanyId: string | null; readonly twentyPersonId: string | null; readonly version: number; };
export type HandOverAcquisitionAssignmentRequest = { readonly revision: number; readonly targetAcquirerUserId: string; };
export type IdentityMembershipResponse = { readonly actionId: string; readonly actionName: string; readonly role: "charity_admin" | "acquirer" | "finance_reader" | "driver"; readonly roleLabel: string; };
export type InvitationAcceptanceResponse = { readonly actionId: string; readonly actionName: string; readonly role: "charity_admin" | "acquirer" | "finance_reader" | "driver"; readonly status: "accepted"; };
export type InvitationDispatchResponse = { readonly invitationId: string; readonly status: "queued"; };
export type InvitationOptionsResponse = { readonly actions: Array<InviteableActionResponse>; readonly roles: Array<InvitationRoleOptionResponse>; };
export type InvitationRevocationResponse = { readonly status: "revoked"; };
export type InvitationRoleOptionResponse = { readonly label: string; readonly value: "charity_admin" | "acquirer" | "finance_reader" | "driver"; };
export type InviteableActionResponse = { readonly id: string; readonly name: string; readonly status: "draft" | "scheduled" | "active"; };
export type InvoiceCancellationResponse = { readonly actionId: string; readonly id: string; readonly invoiceId: string; readonly originalStatus: "issued" | "sent" | "paid"; readonly reason: string; readonly replayed: boolean; readonly requestedAt: string; readonly requestedByDisplayName: string | null; readonly requestedByUserId: string; };
export type InvoiceContextResponse = { readonly actionId: string; readonly actionName: string; readonly endsOn: string; readonly mayIssue: boolean; readonly mayManageSettlements: boolean; readonly profile: InvoiceProfileResponse | null; readonly startsOn: string; };
export type InvoiceCurrencyTotalResponse = { readonly currency: string; readonly grossMinor: number; readonly openMinor: number; };
export type InvoiceDeliveryResponse = { readonly actionId: string; readonly attempts: number; readonly canRetry: boolean; readonly generatedDocumentId: string; readonly id: string; readonly invoiceId: string; readonly lastErrorCode: string | null; readonly lastErrorDetail: string | null; readonly messageId: string | null; readonly recipientEmail: string; readonly requestedAt: string; readonly sentAt: string | null; readonly status: "queued" | "sending" | "retrying" | "failed" | "sent"; readonly subject: string; };
export type InvoiceIssuerResponse = { readonly city: string; readonly countryCode: string; readonly email: string; readonly legalName: string; readonly postalCode: string; readonly streetLine1: string; readonly taxIdentifier: string; };
export type InvoiceLineResponse = { readonly currency: string; readonly description: string; readonly grossMinor: number; readonly netMinor: number; readonly quantity: number; readonly taxMinor: number; readonly taxRateBasisPoints: number; readonly unit: "box" | "piece" | "package" | "sponsoring"; readonly unitPriceGrossMinor: number; };
export type InvoiceListResponse = { readonly actionId: string; readonly currencyTotals: Array<InvoiceCurrencyTotalResponse>; readonly items: Array<InvoiceRecordResponse>; };
export type InvoicePaymentResponse = { readonly actionId: string; readonly amountMinor: number; readonly currency: string; readonly id: string; readonly invoiceId: string; readonly receivedOn: string; readonly recordedAt: string; readonly recordedByDisplayName: string | null; readonly recordedByUserId: string; readonly reference: string; readonly replayed: boolean; };
export type InvoiceProfileResponse = { readonly confirmedAt: string | null; readonly issuer: InvoiceIssuerResponse; readonly nextInvoiceNumber: string; readonly paymentTermsDays: number; readonly readyToIssue: boolean; readonly taxNote: string; readonly taxRateBasisPoints: number; readonly taxTreatment: "standard_vat" | "small_business" | "tax_exempt"; };
export type InvoiceRecordResponse = { readonly buyerDisplayName: string; readonly cancellation: InvoiceCancellationResponse | null; readonly deliveries: Array<InvoiceDeliveryResponse>; readonly invoice: InvoiceResponse; readonly openMinor: number; readonly payment: InvoicePaymentResponse | null; };
export type InvoiceResponse = { readonly actionId: string; readonly approvedByUserId: string; readonly commitmentId: string; readonly currency: string; readonly dueOn: string; readonly grossMinor: number; readonly id: string; readonly issuedAt: string; readonly issuer: InvoiceIssuerResponse; readonly lines: Array<InvoiceLineResponse>; readonly netMinor: number; readonly number: string; readonly paymentReference: string; readonly recipient: CommitmentInvoiceRecipientResponse; readonly replayed: boolean; readonly serviceOn: string; readonly status: "issued" | "sent" | "paid" | "cancelled"; readonly taxMinor: number; readonly taxNote: string; readonly taxTreatment: "standard_vat" | "small_business" | "tax_exempt"; };
export type IssueInvoiceRequest = { readonly serviceOn: string; };
export type LoginDispatchResponse = { readonly status: "queued"; };
export type LogoutResponse = { readonly status: "signed_out"; };
export type MemberDirectoryActionResponse = { readonly actionId: string; readonly actionName: string; };
export type MemberDirectoryMemberResponse = { readonly actionMemberships: Array<MemberDirectoryMembershipResponse>; readonly activeSessionCount: number; readonly displayName: string; readonly email: string; readonly globalRoleLabels: Array<string>; readonly globalRoles: Array<"system_admin" | "finance_reader" | "finance_manager">; readonly lastLoginAt: string | null; readonly status: "invited" | "active" | "suspended" | "archived"; readonly statusLabel: string; readonly userId: string; };
export type MemberDirectoryMembershipResponse = { readonly actionId: string; readonly actionName: string; readonly role: "charity_admin" | "acquirer" | "finance_reader" | "driver"; readonly roleLabel: string; };
export type MemberDirectoryResponse = { readonly actions: Array<MemberDirectoryActionResponse>; readonly items: Array<MemberDirectoryMemberResponse>; readonly nextCursor: string | null; readonly partial: boolean; readonly total: number; };
export type NavigationItemResponse = { readonly href: string; readonly key: string; readonly label: string; readonly surface: "web" | "pwa"; };
export type OperationalApiMetricsResponse = { readonly averageLatencyMs: number; readonly errors: number; readonly requests: number; };
export type OperationalDependencyResponse = { readonly dependency: "twenty" | "rustfs" | "mail"; readonly errorCode: string | null; readonly latencyMs: number; readonly requestId: string; readonly status: "ready" | "unavailable"; };
export type OperationalFailedJobResponse = { readonly aggregateId: string; readonly aggregateType: string; readonly attempts: number; readonly eventType: string; readonly failedAt: string; readonly id: string; readonly lastErrorCode: string; readonly manualRetryCount: number; };
export type OperationalJobRetryResponse = { readonly id: string; readonly manualRetryCount: number; readonly requestId: string; readonly status: "pending"; };
export type OperationalLoginMetricsResponse = { readonly challengesLast24h: number; readonly completionsLast24h: number; readonly failuresLast24h: number; };
export type OperationalStatusCountsResponse = { readonly completed: number; readonly deadLetter: number; readonly pending: number; readonly processing: number; };
export type OperationsOverviewResponse = { readonly api: OperationalApiMetricsResponse; readonly dependencies: Array<OperationalDependencyResponse>; readonly failedJobs: Array<OperationalFailedJobResponse>; readonly generatedAt: string; readonly login: OperationalLoginMetricsResponse; readonly mail: OperationalStatusCountsResponse; readonly outbox: OperationalStatusCountsResponse; readonly requestId: string; };
export type OrderFormConfigurationResponse = { readonly allowMessage: boolean; readonly formKey: string; readonly id: string; readonly introduction: string; readonly requireBillingAddress: boolean; readonly requireCompanyName: boolean; readonly requireContactName: boolean; readonly requireDeliveryAddress: boolean; readonly requireEmail: boolean; readonly requirePhone: boolean; readonly submitLabel: string; readonly title: string; };
export type PlatformInformationResponse = { readonly apiVersion: string; readonly release: string; readonly service: string; };
export type PlatformStatusResponse = { readonly service: string; readonly status: "live"; };
export type PrivacyConsentResponse = { readonly actionId: string | null; readonly channel: "email" | "phone" | "postal"; readonly commitmentId: string | null; readonly evidenceKind: "notice_acknowledgement" | "explicit_consent"; readonly grantedAt: string; readonly id: string; readonly legalBasisStatus: "legal_review_pending" | "confirmed"; readonly purpose: "public_order_fulfilment" | "acquisition" | "marketing"; readonly revokedAt: string | null; readonly source: string; readonly textVersion: string; };
export type PrivacyErasureRequest = { readonly confirmation: string; readonly email: string; };
export type PrivacyErasureResponse = { readonly anonymizedCommitments: number; readonly caseId: string; readonly clearedActivityNotes: number; readonly clearedReminders: number; readonly completedAt: string; readonly openDecisions: Array<string>; readonly retainedDocumentIds: Array<string>; readonly retainedInvoiceIds: Array<string>; readonly retentionReasons: Array<string>; readonly revokedConsents: number; readonly status: "completed_with_retention"; readonly subjectHash: string; };
export type PrivacyReferenceResponse = { readonly actionId: string | null; readonly id: string; readonly label: string; readonly referenceType: "commitment" | "invoice" | "document" | "assignment" | "activity"; readonly status: string | null; };
export type PrivacySubjectReportResponse = { readonly consents: Array<PrivacyConsentResponse>; readonly crmDeletionStatus: "pending_manual_review"; readonly found: boolean; readonly generatedAt: string; readonly openLegalDecisions: Array<string>; readonly references: Array<PrivacyReferenceResponse>; readonly subjectEmail: string; readonly suppressions: Array<PrivacySuppressionResponse>; };
export type PrivacySubjectRequest = { readonly email: string; };
export type PrivacySuppressionResponse = { readonly channel: "email" | "phone" | "postal"; readonly id: string; readonly purpose: "public_order_fulfilment" | "acquisition" | "marketing"; readonly reason: string; readonly suppressedAt: string; };
export type PublicActionRouteResponse = { readonly action: PublicCharityActionResponse | null; readonly availability: "published" | "inactive" | "archive"; readonly canonicalPath: string; readonly routeKind: "alias" | "archive"; readonly routePath: string; readonly routeValue: string; readonly submissionsAllowed: boolean; };
export type PublicCharityActionResponse = { readonly archiveSlug: string; readonly beneficiaries: Array<BeneficiaryResponse>; readonly carrierName: string; readonly endsOn: string; readonly goal: ActionGoalResponse; readonly id: string; readonly name: string; readonly offerings: Array<PublicOfferingResponse>; readonly orderForm: PublicOrderFormResponse | null; readonly purpose: string; readonly startsOn: string; };
export type PublicOfferingResponse = { readonly code: string; readonly currency: string; readonly id: string; readonly name: string; readonly piecesPerUnit: number | null; readonly unit: "box" | "piece" | "package" | "sponsoring"; readonly unitPriceMinor: number; };
export type PublicOrderDeliveryRecipientRequest = { readonly city: string; readonly countryCode?: string; readonly postalCode: string; readonly recipientName: string; readonly streetLine1: string; };
export type PublicOrderFormResponse = { readonly accessToken: string; readonly allowMessage: boolean; readonly formKey: string; readonly introduction: string; readonly requireBillingAddress: boolean; readonly requireCompanyName: boolean; readonly requireContactName: boolean; readonly requireDeliveryAddress: boolean; readonly requireEmail: boolean; readonly requirePhone: boolean; readonly submitLabel: string; readonly title: string; };
export type PublicOrderInvoiceRecipientRequest = { readonly city: string; readonly countryCode?: string; readonly email: string; readonly postalCode: string; readonly recipientName: string; readonly streetLine1: string; };
export type PublicOrderLineRequest = { readonly offeringId: string; readonly quantity: number; readonly quotedUnitPriceMinor: number; readonly unit: "box" | "piece" | "package" | "sponsoring"; };
export type PublicOrderPartyRequest = { readonly companyName?: string | null; readonly email: string; readonly familyName: string; readonly givenName: string; readonly phone?: string | null; };
export type PublicOrderResultResponse = { readonly commitmentId: string; readonly crmOutcome: "created" | "reused"; readonly currency: string; readonly publicReference: string; readonly replayed: boolean; readonly status: "review_ready"; readonly totalBoxes: number; readonly totalMinor: number; readonly totalPieces: number; };
export type ReadinessResponse = { readonly checks: Record<string, DependencyStatusResponse>; readonly service: string; readonly status: "ready" | "not-ready"; };
export type RecordAcquisitionActivityRequest = { readonly channel: "phone" | "email" | "in_person"; readonly dueOn?: string | null; readonly nextAction?: string | null; readonly note?: string | null; readonly outcome: "reached" | "no_answer" | "interested" | "follow_up" | "committed" | "declined"; readonly partyId: string; readonly partyKind: "company" | "person"; readonly revision: number; };
export type RecordAcquisitionActivityResponse = { readonly activity: RecordedAcquisitionActivityResponse; readonly assignment: AcquisitionAssignmentResponse; };
export type RecordInvoicePaymentRequest = { readonly amountMinor: number; readonly currency: string; readonly receivedOn: string; readonly reference: string; };
export type RecordedAcquisitionActivityResponse = { readonly actionId: string; readonly actorDisplayName: string; readonly actorUserId: string; readonly assignmentId: string; readonly assignmentRevision: number; readonly channel: "phone" | "email" | "in_person"; readonly dueAt: string | null; readonly id: string; readonly nextAction: string | null; readonly note: string | null; readonly occurredAt: string; readonly outcome: "reached" | "no_answer" | "interested" | "follow_up" | "committed" | "declined"; readonly partyDisplayName: string; readonly partyId: string; readonly partyKind: "company" | "person"; };
export type RequestLoginRequest = { readonly email: string; };
export type ResolveSponsorMatchRequest = { readonly commandId: string; readonly confirmExistingAssignments?: boolean; readonly expectedStatus: "no_match" | "single_match" | "ambiguous_match"; readonly selectedTwentyId?: string | null; readonly sponsor: SponsorDraftRequest; };
export type RevokePrivacyConsentRequest = { readonly reason: string; };
export type SessionAuthenticationResponse = { readonly displayName: string; readonly expiresAt: string; readonly freshLoginAt: string; readonly status: "authenticated"; readonly userId: string; };
export type SessionRevocationResponse = { readonly revokedCount: number; readonly status: "revoked"; };
export type SetActionBeneficiariesRequest = { readonly beneficiaries: Array<BeneficiaryDraftRequest>; readonly revision: number; };
export type SetActionCapabilitiesRequest = { readonly capabilities: Array<"acquisition" | "offerings" | "ordering" | "invoicing">; readonly revision: number; };
export type SetActionGoalRequest = { readonly actualValue?: string; readonly currency?: string | null; readonly goalValue?: string | null; readonly revision: number; readonly unit?: string | null; };
export type SetActionPublicationRequest = { readonly publicAlias?: string | null; readonly publicationEndsAt?: string | null; readonly publicationStartsAt?: string | null; readonly revision: number; };
export type SetResponsibleAdministratorsRequest = { readonly revision: number; readonly userIds: Array<string>; };
export type SponsorDraftRequest = { readonly city?: string | null; readonly companyName?: string | null; readonly email?: string | null; readonly familyName?: string | null; readonly givenName?: string | null; readonly postalCode?: string | null; readonly streetLine1?: string | null; };
export type SponsorDraftResponse = { readonly city: string | null; readonly companyName: string | null; readonly email: string | null; readonly familyName: string | null; readonly givenName: string | null; readonly postalCode: string | null; readonly streetLine1: string | null; };
export type SponsorMatchCandidateResponse = { readonly assignedAcquirers: Array<AssignedAcquirerResponse>; readonly city: string | null; readonly displayName: string; readonly email: string | null; readonly partyKind: "company" | "person"; readonly postalCode: string | null; readonly twentyId: string; };
export type SponsorMatchResponse = { readonly candidates: Array<SponsorMatchCandidateResponse>; readonly input: SponsorDraftResponse; readonly normalizedKey: string; readonly partyKind: "company" | "person"; readonly status: "no_match" | "single_match" | "ambiguous_match"; };
export type SponsorResolutionResponse = { readonly assignmentCreated: boolean; readonly assignmentId: string; readonly contactTwentyId: string | null; readonly displayName: string; readonly normalizedKey: string; readonly outcome: "created" | "reused"; readonly partyKind: "company" | "person"; readonly priorAssignees: Array<AssignedAcquirerResponse>; readonly replayed: boolean; readonly twentyId: string; };
export type TransitionCharityActionRequest = { readonly revision: number; readonly targetStatus: "draft" | "scheduled" | "active" | "completed" | "archived"; };
export type UpdateAcquisitionAssignmentRequest = { readonly dueAt?: string | null; readonly nextAction?: string | null; readonly priority: number; readonly revision: number; readonly status: "open" | "contacted" | "committed" | "declined"; };
export type UpdateActionDetailsRequest = { readonly carrierName: string; readonly endsOn: string; readonly name: string; readonly purpose: string; readonly revision: number; readonly startsOn: string; };
export type UpdateActivityFeedItemRequest = { readonly read: boolean; };
export type UpdateFeatureFlagRequest = { readonly enabled: boolean; readonly expectedRevision: number; };

export type FetchLike = (
  input: RequestInfo | URL,
  init?: RequestInit,
) => Promise<Response>;

export interface RequestOptions {
  readonly signal?: AbortSignal;
  readonly headers?: Readonly<Record<string, string>>;
}

export class ApiError extends Error {
  readonly status: number;
  readonly detail: ApiErrorDetail;

  constructor(status: number, detail: ApiErrorDetail) {
    super(detail.message);
    this.name = "ApiError";
    this.status = status;
    this.detail = detail;
  }
}

export class LeonAidApiClient {
  readonly #baseUrl: string;
  readonly #fetch: FetchLike;

  constructor(baseUrl: string, fetcher?: FetchLike) {
    this.#baseUrl = baseUrl.replace(/\/$/, "");
    this.#fetch = fetcher ?? globalThis.fetch.bind(globalThis);
  }

  async request<T>(
    path: string,
    init: RequestInit,
    options: RequestOptions = {},
  ): Promise<T> {
    const response = await this.#fetch(`${this.#baseUrl}${path}`, {
      ...init,
      headers: {
        Accept: "application/json",
        ...(init.headers as Readonly<Record<string, string>> | undefined),
        ...options.headers,
      },
      signal: options.signal,
    });
    const body = await response.json() as unknown;
    if (!response.ok) {
      if (isApiErrorResponse(body)) {
        throw new ApiError(response.status, body.error);
      }
      throw new Error(`LeonAid API returned HTTP ${response.status}`);
    }
    return body as T;
  }

  async requestBlob(
    path: string,
    init: RequestInit,
    options: RequestOptions = {},
  ): Promise<Blob> {
    const response = await this.#fetch(`${this.#baseUrl}${path}`, {
      ...init,
      headers: {
        Accept: "application/pdf",
        ...(init.headers as Readonly<Record<string, string>> | undefined),
        ...options.headers,
      },
      signal: options.signal,
    });
    if (!response.ok) {
      const contentType = response.headers.get("content-type") ?? "";
      const body = contentType.includes("application/json")
        ? await response.json() as unknown
        : undefined;
      if (isApiErrorResponse(body)) {
        throw new ApiError(response.status, body.error);
      }
      throw new Error(`LeonAid API returned HTTP ${response.status}`);
    }
    return response.blob();
  }

  async listActionTemplates(
    options: RequestOptions = {},
  ): Promise<ActionTemplateListResponse> {
    return this.request<ActionTemplateListResponse>(
      "/api/v1/action-templates",
      { method: "GET" },
      options,
    );
  }

  async createCharityAction(
    body: CreateCharityActionRequest,
    options: RequestOptions = {},
  ): Promise<CharityActionResponse> {
    return this.request<CharityActionResponse>(
      "/api/v1/actions",
      {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
      },
      options,
    );
  }

  async createCharityActionFromTemplate(
    body: CreateActionFromTemplateRequest,
    options: RequestOptions = {},
  ): Promise<CharityActionConfigurationResponse> {
    return this.request<CharityActionConfigurationResponse>(
      "/api/v1/actions/from-template",
      {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
      },
      options,
    );
  }

  async getCharityAction(
    actionId: string,
    options: RequestOptions = {},
  ): Promise<CharityActionResponse> {
    return this.request<CharityActionResponse>(
      `/api/v1/actions/${encodeURIComponent(String(actionId))}`,
      { method: "GET" },
      options,
    );
  }

  async listAcquisitionActivities(
    actionId: string,
    queryParameters: { readonly offset?: number; readonly limit?: number; } = {},
    options: RequestOptions = {},
  ): Promise<AcquisitionActivityListResponse> {
    const searchParameters = new URLSearchParams();
    if (queryParameters.offset !== undefined && queryParameters.offset !== null) {
      searchParameters.set("offset", String(queryParameters.offset));
    }
    if (queryParameters.limit !== undefined && queryParameters.limit !== null) {
      searchParameters.set("limit", String(queryParameters.limit));
    }
    const queryString = searchParameters.toString();
    const requestPath = `/api/v1/actions/${encodeURIComponent(String(actionId))}/acquisition/activities` + (queryString ? `?${queryString}` : "");
    return this.request<AcquisitionActivityListResponse>(
      requestPath,
      { method: "GET" },
      options,
    );
  }

  async recordAcquisitionActivity(
    actionId: string,
    body: RecordAcquisitionActivityRequest,
    options: RequestOptions = {},
  ): Promise<RecordAcquisitionActivityResponse> {
    return this.request<RecordAcquisitionActivityResponse>(
      `/api/v1/actions/${encodeURIComponent(String(actionId))}/acquisition/activities`,
      {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
      },
      options,
    );
  }

  async getAcquisitionActivityBoard(
    actionId: string,
    queryParameters: { readonly limit?: number; readonly scope?: "personal" | "action"; } = {},
    options: RequestOptions = {},
  ): Promise<AcquisitionActivityBoardResponse> {
    const searchParameters = new URLSearchParams();
    if (queryParameters.limit !== undefined && queryParameters.limit !== null) {
      searchParameters.set("limit", String(queryParameters.limit));
    }
    if (queryParameters.scope !== undefined && queryParameters.scope !== null) {
      searchParameters.set("scope", String(queryParameters.scope));
    }
    const queryString = searchParameters.toString();
    const requestPath = `/api/v1/actions/${encodeURIComponent(String(actionId))}/acquisition/activity-board` + (queryString ? `?${queryString}` : "");
    return this.request<AcquisitionActivityBoardResponse>(
      requestPath,
      { method: "GET" },
      options,
    );
  }

  async createAcquisitionAssignment(
    actionId: string,
    body: CreateAcquisitionAssignmentRequest,
    options: RequestOptions = {},
  ): Promise<AcquisitionAssignmentMutationResponse> {
    return this.request<AcquisitionAssignmentMutationResponse>(
      `/api/v1/actions/${encodeURIComponent(String(actionId))}/acquisition/assignments`,
      {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
      },
      options,
    );
  }

  async getAcquisitionAssignment(
    actionId: string,
    assignmentId: string,
    options: RequestOptions = {},
  ): Promise<AcquisitionAssignmentDetailsResponse> {
    return this.request<AcquisitionAssignmentDetailsResponse>(
      `/api/v1/actions/${encodeURIComponent(String(actionId))}/acquisition/assignments/${encodeURIComponent(String(assignmentId))}`,
      { method: "GET" },
      options,
    );
  }

  async updateAcquisitionAssignment(
    actionId: string,
    assignmentId: string,
    body: UpdateAcquisitionAssignmentRequest,
    options: RequestOptions = {},
  ): Promise<AcquisitionAssignmentResponse> {
    return this.request<AcquisitionAssignmentResponse>(
      `/api/v1/actions/${encodeURIComponent(String(actionId))}/acquisition/assignments/${encodeURIComponent(String(assignmentId))}`,
      {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
      },
      options,
    );
  }

  async handOverAcquisitionAssignment(
    actionId: string,
    assignmentId: string,
    body: HandOverAcquisitionAssignmentRequest,
    options: RequestOptions = {},
  ): Promise<AcquisitionAssignmentHandoverResponse> {
    return this.request<AcquisitionAssignmentHandoverResponse>(
      `/api/v1/actions/${encodeURIComponent(String(actionId))}/acquisition/assignments/${encodeURIComponent(String(assignmentId))}/handover`,
      {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
      },
      options,
    );
  }

  async getAcquisitionDocument(
    actionId: string,
    documentId: string,
    options: RequestOptions = {},
  ): Promise<AcquisitionDocumentResponse> {
    return this.request<AcquisitionDocumentResponse>(
      `/api/v1/actions/${encodeURIComponent(String(actionId))}/acquisition/documents/${encodeURIComponent(String(documentId))}`,
      { method: "GET" },
      options,
    );
  }

  async listAcquisitionParties(
    actionId: string,
    queryParameters: { readonly q?: string | null; readonly offset?: number; readonly limit?: number; } = {},
    options: RequestOptions = {},
  ): Promise<AcquisitionPartyListResponse> {
    const searchParameters = new URLSearchParams();
    if (queryParameters.q !== undefined && queryParameters.q !== null) {
      searchParameters.set("q", String(queryParameters.q));
    }
    if (queryParameters.offset !== undefined && queryParameters.offset !== null) {
      searchParameters.set("offset", String(queryParameters.offset));
    }
    if (queryParameters.limit !== undefined && queryParameters.limit !== null) {
      searchParameters.set("limit", String(queryParameters.limit));
    }
    const queryString = searchParameters.toString();
    const requestPath = `/api/v1/actions/${encodeURIComponent(String(actionId))}/acquisition/parties` + (queryString ? `?${queryString}` : "");
    return this.request<AcquisitionPartyListResponse>(
      requestPath,
      { method: "GET" },
      options,
    );
  }

  async countAcquisitionParties(
    actionId: string,
    queryParameters: { readonly q?: string | null; } = {},
    options: RequestOptions = {},
  ): Promise<AcquisitionPartyCountResponse> {
    const searchParameters = new URLSearchParams();
    if (queryParameters.q !== undefined && queryParameters.q !== null) {
      searchParameters.set("q", String(queryParameters.q));
    }
    const queryString = searchParameters.toString();
    const requestPath = `/api/v1/actions/${encodeURIComponent(String(actionId))}/acquisition/parties/count` + (queryString ? `?${queryString}` : "");
    return this.request<AcquisitionPartyCountResponse>(
      requestPath,
      { method: "GET" },
      options,
    );
  }

  async exportAcquisitionParties(
    actionId: string,
    queryParameters: { readonly q?: string | null; } = {},
    options: RequestOptions = {},
  ): Promise<AcquisitionPartyExportResponse> {
    const searchParameters = new URLSearchParams();
    if (queryParameters.q !== undefined && queryParameters.q !== null) {
      searchParameters.set("q", String(queryParameters.q));
    }
    const queryString = searchParameters.toString();
    const requestPath = `/api/v1/actions/${encodeURIComponent(String(actionId))}/acquisition/parties/export` + (queryString ? `?${queryString}` : "");
    return this.request<AcquisitionPartyExportResponse>(
      requestPath,
      { method: "GET" },
      options,
    );
  }

  async getAcquisitionParty(
    actionId: string,
    partyKind: CrmPartyKind,
    partyId: string,
    options: RequestOptions = {},
  ): Promise<AcquisitionPartyResponse> {
    return this.request<AcquisitionPartyResponse>(
      `/api/v1/actions/${encodeURIComponent(String(actionId))}/acquisition/parties/${encodeURIComponent(String(partyKind))}/${encodeURIComponent(String(partyId))}`,
      { method: "GET" },
      options,
    );
  }

  async previewSponsorMatch(
    actionId: string,
    body: SponsorDraftRequest,
    options: RequestOptions = {},
  ): Promise<SponsorMatchResponse> {
    return this.request<SponsorMatchResponse>(
      `/api/v1/actions/${encodeURIComponent(String(actionId))}/acquisition/sponsor-match`,
      {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
      },
      options,
    );
  }

  async resolveSponsorMatch(
    actionId: string,
    body: ResolveSponsorMatchRequest,
    options: RequestOptions = {},
  ): Promise<SponsorResolutionResponse> {
    return this.request<SponsorResolutionResponse>(
      `/api/v1/actions/${encodeURIComponent(String(actionId))}/acquisition/sponsor-match/resolve`,
      {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
      },
      options,
    );
  }

  async setCharityActionBeneficiaries(
    actionId: string,
    body: SetActionBeneficiariesRequest,
    options: RequestOptions = {},
  ): Promise<CharityActionResponse> {
    return this.request<CharityActionResponse>(
      `/api/v1/actions/${encodeURIComponent(String(actionId))}/beneficiaries`,
      {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
      },
      options,
    );
  }

  async setCharityActionCapabilities(
    actionId: string,
    body: SetActionCapabilitiesRequest,
    options: RequestOptions = {},
  ): Promise<CharityActionResponse> {
    return this.request<CharityActionResponse>(
      `/api/v1/actions/${encodeURIComponent(String(actionId))}/capabilities`,
      {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
      },
      options,
    );
  }

  async getCommitmentCaptureContext(
    actionId: string,
    options: RequestOptions = {},
  ): Promise<CommitmentCaptureContextResponse> {
    return this.request<CommitmentCaptureContextResponse>(
      `/api/v1/actions/${encodeURIComponent(String(actionId))}/commitment-capture`,
      { method: "GET" },
      options,
    );
  }

  async listCommitments(
    actionId: string,
    options: RequestOptions = {},
  ): Promise<CommitmentListResponse> {
    return this.request<CommitmentListResponse>(
      `/api/v1/actions/${encodeURIComponent(String(actionId))}/commitments`,
      { method: "GET" },
      options,
    );
  }

  async createCommitment(
    actionId: string,
    body: CreateCommitmentRequest,
    options: RequestOptions = {},
  ): Promise<CommitmentResponse> {
    return this.request<CommitmentResponse>(
      `/api/v1/actions/${encodeURIComponent(String(actionId))}/commitments`,
      {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
      },
      options,
    );
  }

  async listCommitmentDocuments(
    actionId: string,
    commitmentId: string,
    options: RequestOptions = {},
  ): Promise<GeneratedDocumentListResponse> {
    return this.request<GeneratedDocumentListResponse>(
      `/api/v1/actions/${encodeURIComponent(String(actionId))}/commitments/${encodeURIComponent(String(commitmentId))}/documents`,
      { method: "GET" },
      options,
    );
  }

  async issueInvoice(
    actionId: string,
    commitmentId: string,
    body: IssueInvoiceRequest,
    options: RequestOptions = {},
  ): Promise<InvoiceResponse> {
    return this.request<InvoiceResponse>(
      `/api/v1/actions/${encodeURIComponent(String(actionId))}/commitments/${encodeURIComponent(String(commitmentId))}/invoice`,
      {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
      },
      options,
    );
  }

  async getCharityActionConfiguration(
    actionId: string,
    options: RequestOptions = {},
  ): Promise<CharityActionConfigurationResponse> {
    return this.request<CharityActionConfigurationResponse>(
      `/api/v1/actions/${encodeURIComponent(String(actionId))}/configuration`,
      { method: "GET" },
      options,
    );
  }

  async copyCharityAction(
    actionId: string,
    body: CopyCharityActionRequest,
    options: RequestOptions = {},
  ): Promise<CharityActionConfigurationResponse> {
    return this.request<CharityActionConfigurationResponse>(
      `/api/v1/actions/${encodeURIComponent(String(actionId))}/copies`,
      {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
      },
      options,
    );
  }

  async listCompanyDocuments(
    actionId: string,
    companyId: string,
    options: RequestOptions = {},
  ): Promise<GeneratedDocumentListResponse> {
    return this.request<GeneratedDocumentListResponse>(
      `/api/v1/actions/${encodeURIComponent(String(actionId))}/crm/companies/${encodeURIComponent(String(companyId))}/documents`,
      { method: "GET" },
      options,
    );
  }

  async listPersonDocuments(
    actionId: string,
    personId: string,
    options: RequestOptions = {},
  ): Promise<GeneratedDocumentListResponse> {
    return this.request<GeneratedDocumentListResponse>(
      `/api/v1/actions/${encodeURIComponent(String(actionId))}/crm/people/${encodeURIComponent(String(personId))}/documents`,
      { method: "GET" },
      options,
    );
  }

  async getActionDashboard(
    actionId: string,
    options: RequestOptions = {},
  ): Promise<DashboardResponse> {
    return this.request<DashboardResponse>(
      `/api/v1/actions/${encodeURIComponent(String(actionId))}/dashboard`,
      { method: "GET" },
      options,
    );
  }

  async setCharityActionDetails(
    actionId: string,
    body: UpdateActionDetailsRequest,
    options: RequestOptions = {},
  ): Promise<CharityActionResponse> {
    return this.request<CharityActionResponse>(
      `/api/v1/actions/${encodeURIComponent(String(actionId))}/details`,
      {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
      },
      options,
    );
  }

  async listActionDocuments(
    actionId: string,
    options: RequestOptions = {},
  ): Promise<GeneratedDocumentListResponse> {
    return this.request<GeneratedDocumentListResponse>(
      `/api/v1/actions/${encodeURIComponent(String(actionId))}/documents`,
      { method: "GET" },
      options,
    );
  }

  async downloadGeneratedDocument(
    actionId: string,
    documentId: string,
    queryParameters: { readonly inline?: boolean; } = {},
    options: RequestOptions = {},
  ): Promise<Blob> {
    const searchParameters = new URLSearchParams();
    if (queryParameters.inline !== undefined && queryParameters.inline !== null) {
      searchParameters.set("inline", String(queryParameters.inline));
    }
    const queryString = searchParameters.toString();
    const requestPath = `/api/v1/actions/${encodeURIComponent(String(actionId))}/documents/${encodeURIComponent(String(documentId))}/download` + (queryString ? `?${queryString}` : "");
    return this.requestBlob(
      requestPath,
      { method: "GET" },
      options,
    );
  }

  async setCharityActionGoal(
    actionId: string,
    body: SetActionGoalRequest,
    options: RequestOptions = {},
  ): Promise<CharityActionResponse> {
    return this.request<CharityActionResponse>(
      `/api/v1/actions/${encodeURIComponent(String(actionId))}/goal`,
      {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
      },
      options,
    );
  }

  async getInvoiceContext(
    actionId: string,
    options: RequestOptions = {},
  ): Promise<InvoiceContextResponse> {
    return this.request<InvoiceContextResponse>(
      `/api/v1/actions/${encodeURIComponent(String(actionId))}/invoice-context`,
      { method: "GET" },
      options,
    );
  }

  async listInvoices(
    actionId: string,
    options: RequestOptions = {},
  ): Promise<InvoiceListResponse> {
    return this.request<InvoiceListResponse>(
      `/api/v1/actions/${encodeURIComponent(String(actionId))}/invoices`,
      { method: "GET" },
      options,
    );
  }

  async cancelInvoice(
    actionId: string,
    invoiceId: string,
    body: CancelInvoiceRequest,
    options: RequestOptions = {},
  ): Promise<InvoiceCancellationResponse> {
    return this.request<InvoiceCancellationResponse>(
      `/api/v1/actions/${encodeURIComponent(String(actionId))}/invoices/${encodeURIComponent(String(invoiceId))}/cancellation`,
      {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
      },
      options,
    );
  }

  async sendInvoice(
    actionId: string,
    invoiceId: string,
    options: RequestOptions = {},
  ): Promise<InvoiceDeliveryResponse> {
    return this.request<InvoiceDeliveryResponse>(
      `/api/v1/actions/${encodeURIComponent(String(actionId))}/invoices/${encodeURIComponent(String(invoiceId))}/deliveries`,
      { method: "POST" },
      options,
    );
  }

  async retryInvoiceDelivery(
    actionId: string,
    invoiceId: string,
    deliveryId: string,
    options: RequestOptions = {},
  ): Promise<InvoiceDeliveryResponse> {
    return this.request<InvoiceDeliveryResponse>(
      `/api/v1/actions/${encodeURIComponent(String(actionId))}/invoices/${encodeURIComponent(String(invoiceId))}/deliveries/${encodeURIComponent(String(deliveryId))}/retry`,
      { method: "POST" },
      options,
    );
  }

  async listInvoiceDocuments(
    actionId: string,
    invoiceId: string,
    options: RequestOptions = {},
  ): Promise<GeneratedDocumentListResponse> {
    return this.request<GeneratedDocumentListResponse>(
      `/api/v1/actions/${encodeURIComponent(String(actionId))}/invoices/${encodeURIComponent(String(invoiceId))}/documents`,
      { method: "GET" },
      options,
    );
  }

  async recordInvoicePayment(
    actionId: string,
    invoiceId: string,
    body: RecordInvoicePaymentRequest,
    options: RequestOptions = {},
  ): Promise<InvoicePaymentResponse> {
    return this.request<InvoicePaymentResponse>(
      `/api/v1/actions/${encodeURIComponent(String(actionId))}/invoices/${encodeURIComponent(String(invoiceId))}/payments`,
      {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
      },
      options,
    );
  }

  async getCharityActionManagement(
    actionId: string,
    options: RequestOptions = {},
  ): Promise<ActionManagementResponse> {
    return this.request<ActionManagementResponse>(
      `/api/v1/actions/${encodeURIComponent(String(actionId))}/management`,
      { method: "GET" },
      options,
    );
  }

  async setCharityActionPublication(
    actionId: string,
    body: SetActionPublicationRequest,
    options: RequestOptions = {},
  ): Promise<ActionManagementResponse> {
    return this.request<ActionManagementResponse>(
      `/api/v1/actions/${encodeURIComponent(String(actionId))}/publication`,
      {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
      },
      options,
    );
  }

  async setCharityActionResponsibleAdministrators(
    actionId: string,
    body: SetResponsibleAdministratorsRequest,
    options: RequestOptions = {},
  ): Promise<ActionManagementResponse> {
    return this.request<ActionManagementResponse>(
      `/api/v1/actions/${encodeURIComponent(String(actionId))}/responsible-administrators`,
      {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
      },
      options,
    );
  }

  async transitionCharityAction(
    actionId: string,
    body: TransitionCharityActionRequest,
    options: RequestOptions = {},
  ): Promise<CharityActionResponse> {
    return this.request<CharityActionResponse>(
      `/api/v1/actions/${encodeURIComponent(String(actionId))}/transitions`,
      {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
      },
      options,
    );
  }

  async getActivityFeed(
    queryParameters: { readonly status?: "all" | "unread"; readonly offset?: number; readonly limit?: number; } = {},
    options: RequestOptions = {},
  ): Promise<ActivityFeedResponse> {
    const searchParameters = new URLSearchParams();
    if (queryParameters.status !== undefined && queryParameters.status !== null) {
      searchParameters.set("status", String(queryParameters.status));
    }
    if (queryParameters.offset !== undefined && queryParameters.offset !== null) {
      searchParameters.set("offset", String(queryParameters.offset));
    }
    if (queryParameters.limit !== undefined && queryParameters.limit !== null) {
      searchParameters.set("limit", String(queryParameters.limit));
    }
    const queryString = searchParameters.toString();
    const requestPath = "/api/v1/activity-feed" + (queryString ? `?${queryString}` : "");
    return this.request<ActivityFeedResponse>(
      requestPath,
      { method: "GET" },
      options,
    );
  }

  async updateActivityFeedItem(
    eventId: string,
    body: UpdateActivityFeedItemRequest,
    options: RequestOptions = {},
  ): Promise<ActivityFeedItemResponse> {
    return this.request<ActivityFeedItemResponse>(
      `/api/v1/activity-feed/${encodeURIComponent(String(eventId))}`,
      {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
      },
      options,
    );
  }

  async listFeatureFlags(
    options: RequestOptions = {},
  ): Promise<FeatureFlagAdminListResponse> {
    return this.request<FeatureFlagAdminListResponse>(
      "/api/v1/admin/feature-flags",
      { method: "GET" },
      options,
    );
  }

  async updateFeatureFlag(
    key: string,
    body: UpdateFeatureFlagRequest,
    options: RequestOptions = {},
  ): Promise<FeatureFlagAdminResponse> {
    return this.request<FeatureFlagAdminResponse>(
      `/api/v1/admin/feature-flags/${encodeURIComponent(String(key))}`,
      {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
      },
      options,
    );
  }

  async listMembers(
    queryParameters: { readonly search?: string; readonly status?: "invited" | "active" | "suspended" | "archived" | null; readonly actionId?: string | null; readonly cursor?: string | null; readonly limit?: number; } = {},
    options: RequestOptions = {},
  ): Promise<MemberDirectoryResponse> {
    const searchParameters = new URLSearchParams();
    if (queryParameters.search !== undefined && queryParameters.search !== null) {
      searchParameters.set("search", String(queryParameters.search));
    }
    if (queryParameters.status !== undefined && queryParameters.status !== null) {
      searchParameters.set("status", String(queryParameters.status));
    }
    if (queryParameters.actionId !== undefined && queryParameters.actionId !== null) {
      searchParameters.set("action_id", String(queryParameters.actionId));
    }
    if (queryParameters.cursor !== undefined && queryParameters.cursor !== null) {
      searchParameters.set("cursor", String(queryParameters.cursor));
    }
    if (queryParameters.limit !== undefined && queryParameters.limit !== null) {
      searchParameters.set("limit", String(queryParameters.limit));
    }
    const queryString = searchParameters.toString();
    const requestPath = "/api/v1/admin/members" + (queryString ? `?${queryString}` : "");
    return this.request<MemberDirectoryResponse>(
      requestPath,
      { method: "GET" },
      options,
    );
  }

  async getMember(
    userId: string,
    options: RequestOptions = {},
  ): Promise<MemberDirectoryMemberResponse> {
    return this.request<MemberDirectoryMemberResponse>(
      `/api/v1/admin/members/${encodeURIComponent(String(userId))}`,
      { method: "GET" },
      options,
    );
  }

  async getOperationsOverview(
    options: RequestOptions = {},
  ): Promise<OperationsOverviewResponse> {
    return this.request<OperationsOverviewResponse>(
      "/api/v1/admin/operations",
      { method: "GET" },
      options,
    );
  }

  async retryOperationalJob(
    eventId: string,
    options: RequestOptions = {},
  ): Promise<OperationalJobRetryResponse> {
    return this.request<OperationalJobRetryResponse>(
      `/api/v1/admin/operations/jobs/${encodeURIComponent(String(eventId))}/retry`,
      { method: "POST" },
      options,
    );
  }

  async revokePrivacyConsent(
    consentId: string,
    body: RevokePrivacyConsentRequest,
    options: RequestOptions = {},
  ): Promise<PrivacyConsentResponse> {
    return this.request<PrivacyConsentResponse>(
      `/api/v1/admin/privacy/consents/${encodeURIComponent(String(consentId))}/revoke`,
      {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
      },
      options,
    );
  }

  async erasePrivacySubject(
    body: PrivacyErasureRequest,
    options: RequestOptions = {},
  ): Promise<PrivacyErasureResponse> {
    return this.request<PrivacyErasureResponse>(
      "/api/v1/admin/privacy/erasures",
      {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
      },
      options,
    );
  }

  async exportPrivacySubject(
    body: PrivacySubjectRequest,
    options: RequestOptions = {},
  ): Promise<PrivacySubjectReportResponse> {
    return this.request<PrivacySubjectReportResponse>(
      "/api/v1/admin/privacy/exports",
      {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
      },
      options,
    );
  }

  async lookupPrivacySubject(
    body: PrivacySubjectRequest,
    options: RequestOptions = {},
  ): Promise<PrivacySubjectReportResponse> {
    return this.request<PrivacySubjectReportResponse>(
      "/api/v1/admin/privacy/lookup",
      {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
      },
      options,
    );
  }

  async getFeatureFlagSystemStatus(
    options: RequestOptions = {},
  ): Promise<FeatureFlagSystemStatusResponse> {
    return this.request<FeatureFlagSystemStatusResponse>(
      "/api/v1/admin/system-status",
      { method: "GET" },
      options,
    );
  }

  async revokeUserSessions(
    userId: string,
    options: RequestOptions = {},
  ): Promise<SessionRevocationResponse> {
    return this.request<SessionRevocationResponse>(
      `/api/v1/admin/users/${encodeURIComponent(String(userId))}/sessions`,
      { method: "DELETE" },
      options,
    );
  }

  async requestFreshLogin(
    options: RequestOptions = {},
  ): Promise<LoginDispatchResponse> {
    return this.request<LoginDispatchResponse>(
      "/api/v1/auth/fresh",
      { method: "POST" },
      options,
    );
  }

  async completeFreshLogin(
    body: CompleteFreshLoginRequest,
    options: RequestOptions = {},
  ): Promise<SessionAuthenticationResponse> {
    return this.request<SessionAuthenticationResponse>(
      "/api/v1/auth/fresh/complete",
      {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
      },
      options,
    );
  }

  async getFreshLoginStatus(
    options: RequestOptions = {},
  ): Promise<FreshLoginStatusResponse> {
    return this.request<FreshLoginStatusResponse>(
      "/api/v1/auth/fresh/status",
      { method: "GET" },
      options,
    );
  }

  async requestLogin(
    body: RequestLoginRequest,
    options: RequestOptions = {},
  ): Promise<LoginDispatchResponse> {
    return this.request<LoginDispatchResponse>(
      "/api/v1/auth/login",
      {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
      },
      options,
    );
  }

  async completeLogin(
    body: CompleteLoginRequest,
    options: RequestOptions = {},
  ): Promise<SessionAuthenticationResponse> {
    return this.request<SessionAuthenticationResponse>(
      "/api/v1/auth/login/complete",
      {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
      },
      options,
    );
  }

  async logout(
    options: RequestOptions = {},
  ): Promise<LogoutResponse> {
    return this.request<LogoutResponse>(
      "/api/v1/auth/logout",
      { method: "POST" },
      options,
    );
  }

  async getFeatureFlagEvaluations(
    queryParameters: { readonly surface?: "web" | "pwa"; } = {},
    options: RequestOptions = {},
  ): Promise<FeatureFlagEvaluationListResponse> {
    const searchParameters = new URLSearchParams();
    if (queryParameters.surface !== undefined && queryParameters.surface !== null) {
      searchParameters.set("surface", String(queryParameters.surface));
    }
    const queryString = searchParameters.toString();
    const requestPath = "/api/v1/feature-flags/evaluations" + (queryString ? `?${queryString}` : "");
    return this.request<FeatureFlagEvaluationListResponse>(
      requestPath,
      { method: "GET" },
      options,
    );
  }

  async getCurrentIdentity(
    options: RequestOptions = {},
  ): Promise<CurrentIdentityResponse> {
    return this.request<CurrentIdentityResponse>(
      "/api/v1/identity/me",
      { method: "GET" },
      options,
    );
  }

  async createInvitation(
    body: CreateInvitationRequest,
    options: RequestOptions = {},
  ): Promise<InvitationDispatchResponse> {
    return this.request<InvitationDispatchResponse>(
      "/api/v1/invitations",
      {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
      },
      options,
    );
  }

  async acceptInvitation(
    body: AcceptInvitationRequest,
    options: RequestOptions = {},
  ): Promise<InvitationAcceptanceResponse> {
    return this.request<InvitationAcceptanceResponse>(
      "/api/v1/invitations/accept",
      {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
      },
      options,
    );
  }

  async getInvitationOptions(
    options: RequestOptions = {},
  ): Promise<InvitationOptionsResponse> {
    return this.request<InvitationOptionsResponse>(
      "/api/v1/invitations/options",
      { method: "GET" },
      options,
    );
  }

  async revokeInvitation(
    invitationId: string,
    options: RequestOptions = {},
  ): Promise<InvitationRevocationResponse> {
    return this.request<InvitationRevocationResponse>(
      `/api/v1/invitations/${encodeURIComponent(String(invitationId))}`,
      { method: "DELETE" },
      options,
    );
  }

  async getPlatformInformation(
    options: RequestOptions = {},
  ): Promise<PlatformInformationResponse> {
    return this.request<PlatformInformationResponse>(
      "/api/v1/platform",
      { method: "GET" },
      options,
    );
  }

  async resolvePublicActionAlias(
    publicAlias: string,
    options: RequestOptions = {},
  ): Promise<PublicActionRouteResponse> {
    return this.request<PublicActionRouteResponse>(
      `/api/v1/public/actions/alias/${encodeURIComponent(String(publicAlias))}`,
      { method: "GET" },
      options,
    );
  }

  async resolvePublicActionArchive(
    archiveSlug: string,
    options: RequestOptions = {},
  ): Promise<PublicActionRouteResponse> {
    return this.request<PublicActionRouteResponse>(
      `/api/v1/public/actions/archive/${encodeURIComponent(String(archiveSlug))}`,
      { method: "GET" },
      options,
    );
  }

  async createPublicOrder(
    publicAlias: string,
    body: CreatePublicOrderRequest,
    options: RequestOptions = {},
  ): Promise<PublicOrderResultResponse> {
    return this.request<PublicOrderResultResponse>(
      `/api/v1/public/actions/${encodeURIComponent(String(publicAlias))}/orders`,
      {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
      },
      options,
    );
  }

  async getHealthLive(
    options: RequestOptions = {},
  ): Promise<PlatformStatusResponse> {
    return this.request<PlatformStatusResponse>(
      "/health/live",
      { method: "GET" },
      options,
    );
  }

  async getHealthReady(
    options: RequestOptions = {},
  ): Promise<ReadinessResponse> {
    return this.request<ReadinessResponse>(
      "/health/ready",
      { method: "GET" },
      options,
    );
  }
}

function isApiErrorResponse(value: unknown): value is ApiErrorResponse {
  if (typeof value !== "object" || value === null || !("error" in value)) {
    return false;
  }
  const error = value.error;
  return typeof error === "object" && error !== null
    && "code" in error && typeof error.code === "string"
    && "message" in error && typeof error.message === "string"
    && "requestId" in error && typeof error.requestId === "string";
}
